onlyBuiltDependencies:
  - core-js
  - dtrace-provider
  - es5-ext
  - fsevents
  - sharp
  - spawn-sync

overrides:
  postcss: "^8.5.10"
  brace-expansion: "^2.0.3"
  tmp: "^0.2.6"
  braces: "^3.0.3"
  micromatch: "^4.0.8"
  "@eslint/plugin-kit": "^0.3.4"
  yauzl: "^3.2.1"
  uuid: "^11.1.1"
